### PR TITLE
:arrow_up: upgrade to v1.5.2

### PR DESCRIPTION
**Pull request by Aeris1One**

### CODE REVIEW

**Comment by Aeris1One** [comment]
!testme

**Comment by Aeris1One** [comment]
!testme

**Comment by Aeris1One** [comment]
!testme

**Comment by Aeris1One** [comment]
I'm so bad at merging conflicts, reverted the whole PR :sob: 
And... another CI run !

**Comment by Aeris1One** [comment]
!testme

**Comment by Aeris1One** [comment]
Tested, it works, but need to wait for Firefly III to upgrade to v6.1.0 before merging.
image

**Comment by OniriCorpe** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
superseded by #25

**Pull request closed without merging**
