### PR TITLE
upgrade to 1.5.2

### PR DESCRIPTION
**Pull request by GannonTdW**
Upgrade to version 1.5.2

### CODE REVIEW

**Comment by GannonTdW** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ballinger** [comment]
Would be great if some1 could fix this

**Comment by ericgaspar** [comment]
!testme

**Comment by ballinger** [comment]
good to merge?

**Comment by GannonTdW** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by GannonTdW** [comment]
hello @ericgaspar,

I don't understand, the  `/var/log/${app}` folder is supposed to be created by what?
I've looked at several application installation scripts and I can't find any `mkdir /var/log/${app}`,
But for example, I  found [chown -R $app:$app /var/log/$app/](https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install)

Can you show me where is the test script for "Validating that the app firefly-iii-di can/can't be accessed with its URL..." ?

And for https://github.com/YunoHost-Apps/firefly-iii-di_ynh/blob/testing/tests.toml : `5a7ffe7` -> `4d02b6f` ?

Thx

**Comment by ballinger** [comment]
Hey, would be great if the last bits could get resolved

**Comment by ballinger** [comment]
looks like the last ynh firefly update is not compatible with the importer...

**Pull request closed without merging**
